scenario: |
  1. 처음 알게 된 계기 ex) 광고, 친구 추천, SKT 공식 홈페이지, 앱스토어
  2. 주로 사용하는 상황 ex) 업무 통화, 중요한 전화, 복잡한 내용의 통화
  3. 사용하는 이유 ex) 편의성, 자동 녹음, 텍스트 요약 기능
  4. 편리하게 느낀 순간 ex) 긴 통화 내용 요약, 중요 포인트 체크
  5. 돋보이는 점 ex) 정확성, 사용자 친화적, 빠른 변환 속도
  6. 불편한 부분 ex) 녹음 퀄리티, 앱 크래시, 저장 공간 문제
  7. 자동녹음의 어려움 여부 ex) 녹음 실패, 자동 저장 문제, 녹음 설정 복잡
  8. 텍스트 변환 오류 여부 ex)잘못된 내용 변환, 중요 정보 누락
  9. 개선 필요한 부분 ex) 더 정확한 변환, 더 빠른 변환 속도, 사용자 설정 기능
  10. 추가 희망 기능 ex) 다양한 언어 지원, 화자 구분 기능, 클라우드 저장
  11. 가장 크게 느낀 점 ex) 통화 관리의 편리성, 시간 절약
  12. 추가 의견 ex) 가격 관련 피드백, 고객 서비스 피드백, 추천할 의향